#!/bin/sh

# This script is used to help manage a main/fallback server pair that
# supports live updates that can occur without forcefully kicking
# players from the server. It's designed to be (at minimum)
# fully POSIX.1-2008 compliant, aside from requiring a few additional
# programs, which are as follows:
#
# * git
# * java
# * rsync
# * tmux
#
# Run 'puppet help' for more info.
#
# STYLE
#
# Prefer one line conditionals like '[ ... ] && command' when
# reasonably possible and does not cause readability concerns. Line
# width should not exceed 70 characters, even for comments. If it is
# necessary to break a single command across multiple lines due to
# this restriction, each argument should be on the same line, except
# in the case of arguments that are logically paired with each other,
# like in case of 'sh -c command'; -c and 'command' are related and
# should go on the same line.
#
# If it is necessary to split command chains, and each command is
# suitably short, add a newline after the conditional, like this:
#
# long_command_that_should_be_split | another_long_command &&
# then_run_this_other_long_command
#
# NOT like this:
# long_command_that_should_be_split | another_long_command
# && then_run_this_other_long_command
#
# GENERAL GUIDELINES
#
# Comment most things unless they are very obvious (and even then,
# consider making a comment). Commented lines should always start with
# a pound sign followed immediately by a space.
#
# Local variables (those used entirely within a function, or not meant
# to be accessed globally) should start with an underscore.
#
# Commands that may fail (due to IO errors or other faulty conditions)
# should typically exit by calling 'die' with an informative error
# message, like this:
#
# command_that_may_err || die "couldn't run the command"
#
# Commands that take one or more file paths as an argument should use
# -- as a separator between any flags and the files, if this is
# supported. Or, if no flags are being used, -- should appear at the
# beginning.
#
# Functions that don't reference global variables should go in the
# UTILITY FUNCTIONS section. They should be alphabetically ordered by
# name. Functions that do reference global variables should go in the
# CONTEXTUAL FUNCTIONS section, likewise alphabetically ordered.

# UTILITY FUNCTIONS (these do not reference global variables)

die () {
    # The first argument is optional. If it's not there, don't print
    # anything, just exit.
    [ -n "$1" ] || exit 1

    # Print the formatted message to stderr.
    msg "\033[31;1m[ERROR]\033[0m %s\n" "[ERROR] %s\n" "$1" 1>&2
    exit 1
}

quote () {
    # This trick for quoting shell variables is taken from
    # https://www.etalabs.net/sh_tricks.html. It neatly escapes any
    # single-quotes in the input as well as surrounding the entire
    # string with them, preventing issues that arise out of trailing
    # newlines being stripped.
    printf "%s\n" "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"
}

msg () {
    # Save the first two parameters because we need to shift them out
    # afterwards.
    _fmt_1="$1"
    _fmt_2="$2"

    shift 2

    # Using variables in format strings is alright here, that's the
    # entire point of this function.
    # shellcheck disable=SC2059
    if [ -t 0 ]; then
        printf "$_fmt_1" "$@"
    else
        printf "$_fmt_2" "$@"
    fi
}

require_non_empty () {
    [ -n "$1" ] || die "missing required configuration"
}

dir_target () {
    # Hacky way to resolve a symbolic link if it's a directory. Used
    # because readlink is not specified in 2008 POSIX, though note
    # that it does exist in later publications.
    #
    # Use a subshell just to prevent changing the current directory of
    # the calling shell.
    #
    # This only works if $1 is a link to a directory, for obvious
    # reasons.
    ( cd -- "$1" > /dev/null || exit 1; pwd -P ) ||
    die "couldn't resolve directory link at $1"
}

safe_cd () {
    # Die if the directory doesn't exist, no permissions, etc. Only
    # redirect stdout to /dev/null because the user probably wants to
    # see what the error message was, if any.
    cd -- "$1" > /dev/null || die "couldn't cd to $1"
}

safe_rm () {
    # Make sure the file exists first.
    [ -e "$1" ] || return

    # Remove a single directory recursively, or die.
    rm -rf -- "$1" || die "couldn't remove directory"
}

# END UTILITY FUNCTIONS

# GLOBAL VARIABLES (these are all readonly)

# Pretty much everything requires our CWD, so just grab it now. The
# result shouldn't contain any symlinks because of the -P flag.
#
# A trailing '.' is added to the output. If our CWD has trailing
# newlines in the path, this will prevent them from being stripped.
current_directory=$( pwd -P || exit 1; printf "." ) ||
die "couldn't get cwd"

# Remove the last two characters, one of which will be a '.', the
# other an additional newline added by 'pwd'. This trick is used
# elsewhere in this script, whenever it is necessary to read a
# filepath from the system.
current_directory="${current_directory%??}"

# User configuration file.
conf_file="$current_directory/puppet.conf"

# Files that differ between server_1 and server_2 live here. These
# are needed to prevent the servers from binding to the same port.
server_1_unique_dir="$current_directory/server_1_unique"
server_2_unique_dir="$current_directory/server_2_unique"

# Files that don't differ between server_1 and server_2 live here.
# However, this doesn't include configuration, code, or generated
# artifacts.
common_dir="$current_directory/common"

# All "internal" files used by Puppet live here. These do not usually
# need to be read or written by users of this script.
puppet_dir="$current_directory/.puppet"

# These are the actual (non-symlink) server directories.
server_dir_1="$puppet_dir/server_1"
server_dir_2="$puppet_dir/server_2"

# Symlinks to $server_dir_1 and $server_dir_2, depending on which is
# active at the time.
main_link="$puppet_dir/main"
fallback_link="$puppet_dir/fallback"

# tmux socket files
socket_file_1="$puppet_dir/socket_1"
socket_file_2="$puppet_dir/socket_2"

# Symlinks to $socket_file_1 and $socket_file_2, depending on which
# is active at the time.
main_socket_link="$puppet_dir/main_socket"
fallback_socket_link="$puppet_dir/fallback_socket"

log_pipe_1="$puppet_dir/log_pipe_1"
log_pipe_2="$puppet_dir/log_pipe_2"

main_log_pipe_link="$puppet_dir/main_log_pipe_link"
fallback_log_pipe_link="$puppet_dir/fallback_log_pipe_link"

# Named pipes, used for IPC; namely, the startup script signals that
# it has either succeeded or failed to start.
status_pipe_1="$puppet_dir/status_pipe_1"
status_pipe_2="$puppet_dir/status_pipe_2"

# Symlinks to $status_pipe_1 and $status_pipe_2. These links should
# always exist, though the pipes that they point to are removed once
# the corresponding server is offline.
main_status_pipe_link="$puppet_dir/main_status_pipe_link"
fallback_status_pipe_link="$puppet_dir/fallback_status_pipe_link"

# Source and configuration git repositories, respectively
src_dir="$puppet_dir/src"
config_dir="$puppet_dir/config"

# The ./run/server-1 directory. This is where the build scripts place
# most generated artifacts; e.g. libraries and the server jar.
build_target_dir="$src_dir/run/server-1"

# Libraries, produced by the Gradle build script.
libs_dir="$build_target_dir/libs"

# The built server.jar file, produced by the Gradle build script.
server_jar="$build_target_dir/server.jar"

# Used to make an exclusive lock.
lock_dir="$puppet_dir/lock"

# A small script file that's generated by this one, and used to
# actually launch the server(s), as well as handling some IPC.
start_file="$puppet_dir/start"

# The name used for both tmux sessions and windows.
tmux_session_name="puppet_server"

# END GLOBAL VARIABLES

# CONTEXTUAL FUNCTIONS

bring_offline () {
    # Send the shutdown command to the server.
    tmux_send_keys "$1" orderly_shutdown

    # Wait for the log file link to be removed. This
    # indicates that the server has shut down, as it is removed only
    # when the wrapper script exits.
    #
    # We wait in a loop, instead of using a FIFO and signalling,
    # because we may end up blocking indefinitely if the server was
    # already shut down.
    while [ -p "$2" ]; do
        sleep 1
    done
}

bring_online () {
    # Both of these are passed to invocations of tmux_send_keys below.
    # Note that we do not have to worry about trailing newlines for
    # calls to quote, because they always end with a single-quote.
    _escaped_cwd=$( quote "$current_directory" )
    _escaped_start_file=$( quote "$start_file" )

    # $_target_id will be either 1 or 2, depending on if $1 is
    # $server_dir_1 or $server_dir_2.
    _target_id=$( sync_target "$1" ) || die

    eval "_status_pipe=\"\$status_pipe_$_target_id\""

    # Start up the server. This literally types the startup command
    # into the tmux terminal.
    tmux_send_keys "$2" \
    "$_escaped_start_file $_escaped_cwd $_target_id"

    # cat will block here until there's some data in the pipe. If the
    # startup script never sends anything, this will deadlock.
    #
    # Also, _status_pipe is assigned but it's through an 'eval'.
    # shellcheck disable=SC2154
    _status=$( cat -u -- "$_status_pipe" ) ||
    die "couldn't read from pipe"

    case "$_status" in
        "OK") ;;
        "ERR")
            # We were able to connect to the pipe, but the process
            # reported an error launching the server, e.g. there was
            # a compiler error.
            die "failed to launch server"
        ;;
        "INTERRUPTED")
            # Sent if the launcher script was interrupted, e.g.
            # through SIGTERM or SIGINT.
            die "launch wrapper was interrupted"
        ;;
        *)
            # This indicates a bug in the starting script that should
            # be fixed.
            die "couldn't recognize status code $_status"
        ;;
    esac
}

promote_fallback () {
    _new_main_dir="$1"

    case "$_new_main_dir" in
        "$server_dir_1")
            _main_id="1"
            _fallback_id="2"
        ;;

        "$server_dir_2")
            _main_id="2"
            _fallback_id="1"
        ;;

        *) die "couldn't recognize server directory $1" ;;
    esac

    eval "_new_main_socket=\"\$socket_file_$_main_id\""
    eval "_new_main_status_pipe=\"\$status_pipe_$_main_id\""
    eval "_new_main_log_pipe=\"\$log_pipe_$_main_id\""

    eval "_new_fallback_dir=\"\$server_dir_$_fallback_id\""
    eval "_new_fallback_socket=\"\$socket_file_$_fallback_id\""
    eval "_new_fallback_status_pipe=\"\$status_pipe_$_fallback_id\""
    eval "_new_fallback_log_pipe=\"\$log_pipe_$_fallback_id\""

    # Update the symbolic links. All of the _new_* variables are
    # assigned in 'eval' calls above.
    # shellcheck disable=SC2154
    (
    ln -sf -- "$_new_main_dir" "$main_link" && \
    ln -sf -- "$_new_fallback_dir" "$fallback_link" && \
    ln -sf -- "$_new_main_socket" "$main_socket_link" && \
    ln -sf -- "$_new_fallback_socket" "$fallback_socket_link" && \
    ln -sf -- "$_new_main_status_pipe" "$main_status_pipe_link" && \
    ln -sf -- "$_new_fallback_status_pipe" \
    "$fallback_status_pipe_link" && \
    ln -sf -- "$_new_main_log_pipe" "$main_log_pipe_link" && \
    ln -sf -- "$_new_fallback_log_pipe" "$fallback_log_pipe_link"
    ) || die "couldn't create symlink(s)"
}

require_code () {
   [ -d "$src_dir/.git" ] || die "src must be brought up to date"
}

require_config () {
   [ -d "$config_dir/.git" ] || die "config must be brought up to date"
}

sync_target () {
    _sync_internal () {
        rsync -ac --delete -- "$1" \
        "$server_jar" \
        "$libs_dir" \
        "$common_dir/" \
        "$config_dir/" \
        "$2" > /dev/null || die "couldn't sync"
    }

    # The only thing that changes for different values of $1 is
    # whether we sync from $server_1_unique_dir or
    # $server_2_unique_dir, or exit with an error (if $1 isn't a value
    # we're expecting).
    case "$1" in
        "$server_dir_1")
            _sync_internal "$server_1_unique_dir/" "$1"
            printf "1"
        ;;

        "$server_dir_2")
            _sync_internal "$server_2_unique_dir/" "$1"
            printf "2"
        ;;

        *) die "invalid target $1" ;;
    esac
}

tmux_attach () {
    tmux -S "$1" attach-session -t "$tmux_session_name"
}

tmux_init () {
    # Creates a tmux session on the socket, if one doesn't exist
    # already.
    if [ ! -S "$1" ] || ! tmux -S "$1" list-sessions \
    -F#\{session_name\} | grep -qF -- "$tmux_session_name"; then
        tmux -S "$1" new-session \
        -d -n "$tmux_session_name" \
        -s "$tmux_session_name"
    fi
}

tmux_send_keys () {
    tmux -S "$1" \
    send-keys \
    -t "$tmux_session_name" \
    "$2" Enter
}

update_config () {
    # If the "reclone" flag '-r' is set, remove the config directory.
    # This will cause the repository to be cloned again, which is
    # useful if the configuration changed to point to a new remote
    # repository. We also do the same thing for update_src below.
    [ -n "$reclone" ] && safe_rm "$config_dir"

    # We check for the .git directory, just to see if we have an
    # actual repository, as opposed to e.g. an empty folder.
    if [ ! -d "$config_dir/.git" ]; then
        safe_rm "$config_dir"

        git clone "$config_repo" "$config_dir" ||
        die "couldn't clone $config_repo"
    fi

    # Use a subshell here so that 'safe_cd' doesn't change our current
    # directory.
    (
    safe_cd "$config_dir"

    git checkout "$config_branch" ||
    die "couldn't checkout $config_branch"

    git pull || die "couldn't pull $config_branch"
    ) || die "couldn't update config"
}

update_src () {
    [ -n "$reclone" ] && safe_rm "$src_dir"

    if [ ! -d "$src_dir/.git" ]; then
        safe_rm "$src_dir"

        git clone --recurse-submodules "$src_repo" "$src_dir" ||
        die "couldn't clone $src_repo"
    fi

    (
    safe_cd "$src_dir"

    git checkout "$src_branch" ||
    die "couldn't checkout $src_branch"

    git pull --recurse-submodules || die "couldn't pull $src_branch"

    ./gradlew --no-daemon \
    -PskipBuild=snbt-builder,dev-launcher,velocity \
    phantazm-server:copyJar \
    phantazm-server:copyLibs || die "couldn't build src"
    ) || die "couldn't update src"
}

# END CONTEXTUAL FUNCTIONS

# USER CONFIGURATION VARIABLES

src_repo=""
src_branch=""

config_repo=""
config_branch=""

# END USER CONFIGURATION VARIABLES

# FLAG PROCESSING

case "$2" in
    "") ;;
    "-r") reclone="TRUE" ;;
    *) die "unrecognized flag $2" ;;
esac

# END FLAG PROCESSING

# SETUP

# All files we make should be readable and writeable by ourselves, but
# not executable, and not readable, writable, or executable to others.
umask 077

if [ "$1" = "setup" ]; then
    # Setup requires user input and so shouldn't be run
    # non-interactively.
    [ -t 0 ] || die "setup must be run interactively"

    # Search the current directory for files that shouldn't be there.
    # This is more of a sanity check than anything, to make sure the
    # user doesn't accidentally clobber an already-populated
    # directory.
    for file in "$current_directory/".* "$current_directory/"*; do
        _basename=$( basename "$file" || exit 1; printf "." ) ||
        die "couldn't get basename of $file"

        _basename="${_basename%??}"

        # Ignore . and .. directory components, and non-existent files
        [ "$_basename" = "." ] && continue
        [ "$_basename" = ".." ] && continue
        [ -e "$file" ] || continue

        # The directory must be empty except for the puppet.conf file.
        if [ "$file" = "$conf_file" ]; then
            # Sanity check: if puppet.conf is a directory then weird
            # things will probably happen.
            [ -f "$file" ] || die "puppet.conf must be a file"
        else
            # Any files other than puppet.conf aren't allowed to be
            # in the folder.
            die "directory must be empty"
        fi
    done

    # We're using $conf_file as a config file, so we don't care if it
    # can be debugged by shellcheck.
    # shellcheck disable=SC1090
    if [ -f "$conf_file" ]; then
        . "$conf_file" || die "couldn't source $conf_file"
    fi

    # Fill in any missing configuration entries as needed. These
    # aren't validated, but the user can always manually edit
    # puppet.conf; generating the config like this is mostly a matter
    # of convenience.
    #
    # Note that $conf_file is allowed to exist, and may already be
    # populated with values. We'll recreate that file, but the old
    # values of $src_repo, $src_branch, $conf_repo, and
    # $conf_branch will be preserved.
    if [ -z "$src_repo" ]; then
        printf "Enter the code repository: "
        read -r src_repo
    fi

    if [ -z "$src_branch" ]; then
        printf "Enter the code branch: "
        read -r src_branch
    fi

    if [ -z "$config_repo" ]; then
        printf "Enter the config repository: "
        read -r config_repo
    fi

    if [ -z "$config_branch" ]; then
        printf "Enter the config branch: "
        read -r config_branch
    fi

    # Make all necessary directories.
    mkdir -- "$puppet_dir" \
    "$server_dir_1" \
    "$server_dir_2" \
    "$server_1_unique_dir" \
    "$server_2_unique_dir" \
    "$common_dir" || die "couldn't make required directories"

    # Set up the named pipes we use for IPC.
    mkfifo -m 600 -- "$status_pipe_1" "$status_pipe_2"

    # Set up the initial symlinks
    (
    ln -s -- "$server_dir_1" "$main_link" && \
    ln -s -- "$server_dir_2" "$fallback_link" && \
    ln -s -- "$socket_file_1" "$main_socket_link" && \
    ln -s -- "$socket_file_2" "$fallback_socket_link" && \
    ln -s -- "$status_pipe_1" "$main_status_pipe_link" && \
    ln -s -- "$status_pipe_2" "$fallback_status_pipe_link" && \
    ln -s -- "$log_pipe_1" "$main_log_pipe_link" && \
    ln -s -- "$log_pipe_2" "$fallback_log_pipe_link"
    ) || die "couldn't create symlink(s)"

    # Generate the config file based on the user's choices. Will have
    # rw------- perms, as per 'umask' above.
    printf "%s" "#!/bin/false
src_repo=$( quote "$src_repo" )
src_branch=$( quote "$src_branch" )
config_repo=$( quote "$config_repo" )
config_branch=$( quote "$config_branch" )" \
> "$conf_file" || die "couldn't generate config file"

    # Generate the starting script. Note that to allow server
    # directories to be freely moved, this file must not contain
    # absolute paths. Instead, paths are derived from the arguments
    # passed into the script.
    #
    # The script uses two named pipes. One is used to send the output
    # of the server to a separate process so that it may be inspected,
    # the other is used to signal either the success or failure state.
    # These are, respectively, $log_pipe and $status_pipe. $log_pipe
    # is used only within the scope of the startup wrapper, and is
    # deleted on exit (though its existence is used to check whether
    # the process is online). $status_pipe is NOT created by the
    # startup wrapper, and is used solely to enable communication
    # between the wrapper and puppet.
    printf "%s" "#!/bin/sh
#
# Generated Puppet wrapper script; do not edit!
#

write_pipe () {
    # Start writing to the pipe in the background, and grab the PID
    # of this child process.
    printf \"%s\\n\" \"\$2\" > \"\$1\" &
    _write_pid=\"\$!\"

    # Start a timer. After the timer elapses, try to kill the printf
    # command.
    { sleep 5; kill \"\$_write_pid\" > /dev/null 2>&1; } &
    _timer_pid=\"\$!\"

    # Either the write succeeded or it got killed by the timer.
    wait \"\$_write_pid\"

    # Clean up the timer process too, in case it isn't already done.
    kill \"\$_timer_pid\" > /dev/null 2>&1
}

puppet_dir=\"\$1/.puppet\"

case \"\$2\" in
    \"1\"|\"2\") ;;

    # Sanity check to make sure we don't try to resolve the wrong
    # files.
    *) exit 1 ;;
esac

# Files we create should also be rw-------
umask 077

server_dir=\"\$puppet_dir/server_\$2\"
log_pipe=\"\$puppet_dir/log_pipe_\$2\"
status_pipe=\"\$puppet_dir/status_pipe_\$2\"

cd -- \"\$server_dir\" || exit 1

# This FIFO is only read/written by child processes of this wrapper
# script. However, its existence is used to determine if we are
# \"running\" or not, so we make sure to delete it on exit.
mkfifo -m 600 -- \"\$log_pipe\" || exit 1

exit_hook () {
    _old_exit_code=\"\$?\"

    # Detect abnormal termination through e.g. SIGINT, SIGQUIT. If
    # this is the case, we MAY not have informed puppet of our
    # impending demise. This is bad because it may be waiting for us
    # to send a message; hence, we signal that here.
    if [ \"\$1\" -ne 0 ]; then
        # Let the user know that their CTRL-C (or whatever it was) was
        # received. We want to discourage them from getting impatient
        # and breaking out kill -9.
        printf \"%s\\n\" \\
        \"Please wait for a maximum of ~5 seconds...\"

        write_pipe \"\$status_pipe\" \"INTERRUPTED\"
        printf \"%s\\n\" \"Shutdown signalled.\"
    fi

    rm -f -- \"\$log_pipe\"
    return \"\$_old_exit_code\"
}

trap 'exit_hook 0' EXIT

# Clear existing traps so exit doesn't cause the hook to run again.
trap 'trap - 0; exit_hook 1; exit' HUP INT QUIT ABRT TERM

inspect_pipe () {
    # Read from the log pipe until we see the \"serverIP\" text. Then,
    # signal \$status_pipe. If we got EOF (because the server process
    # exited) we send ERR. Otherwise, send OK, and redirect the pipe
    # to /dev/null, because we don't care to inspect anything that
    # gets sent over anymore, and not reading from it at all would
    # cause the server process to hang.
    #
    # To prevent deadlocks in case nobody's listening on the other
    # end, write_pipe will wait a maximum of 5 seconds for the OK or
    # ERR signal to go through.
    if grep -qF \"serverIP\" \"\$log_pipe\"; then
        write_pipe \"\$status_pipe\" \"OK\"
    else
        write_pipe \"\$status_pipe\" \"ERR\"
        return
    fi

    # Any more output produced by the server process should be
    # consumed, or else it would hang. So just redirect everything to
    # /dev/null.
    #
    # This process will exit normally, due to cat receiving an EOF,
    # when the process writing to \$log_pipe dies. In our case, that's
    # a 'tee' call.
    cat -u -- \"\$log_pipe\" > /dev/null 2>&1
}

server () {
    java -Dfile.encoding=UTF-8 -jar server.jar
}

# Run the server as a background process. Because backgrounded
# processes have their stdin set to (an equivalent of?) /dev/null by
# default, create a copy of stdin on file descriptor 3, and redirect
# that to the server process. Also redirect its stdout to FD 4, which
# allows us to connect its log output to tee (which also runs in a
# background process).
#
# Using tee like this is needed because not only do we want the log
# output of the server to be written to a pipe for later consumption,
# we want it to be written to our stdout.
#
# Why not simply write something like 'server | tee -- \$log_pipe'?
# Because we need to get the process ID of the server process, not
# just tee. We grab tee's PID too, though, because it will not exit
# when the server does.
{
    server <&3 >&4 &
    server_pid=\"\$!\"

    tee -- \"\$log_pipe\" <&4 &
    tee_pid=\"\$!\"
} 3<&0 4>&1

# Start listening to the server output on a background process.
inspect_pipe &
inspect_pid=\"\$!\"

# Wait on the server process first.
wait \"\$server_pid\"

# Kill tee, which is the process actually writing to \$log_pipe. Note
# that this will cause the reader of \$log_pipe to EOF, which is what
# is intended.
kill \"\$tee_pid\" > /dev/null 2>&1

# Wait for the inspect_pipe function to finish whatever it's doing.
# This may be a 'cat' (if the server launched successfully) or a
# 'grep' (if the server didn't launch and we're still waiting on the
# log output). We also might be presently communicating with Puppet,
# by indicating the error status.
wait \"\$inspect_pid\"
" > "$start_file" || die "couldn't generate $start_file"

    # $start_file has to be executable.
    chmod 700 -- "$start_file" ||
    die "couldn't set permissions on $start_file"

    printf "Setup completed successfully.\n"
    exit 0
fi

# END SETUP

# Help can always be run, even if the user hasn't set up Puppet in
# the current directory yet.
if [ "$1" = "help" ]; then
    printf "%s\n" "USAGE: puppet <option> [-r]

This script is used to orchestrate Phantazm servers. Updates can be
deployed without requiring a hard restart and without interrupting
existing games. Also provides utilities for attaching to the terminals
associate with the servers.

SETUP
To set up puppet in an existing directory, run 'puppet setup' in an
interactive terminal, and follow the setup instructions. You can run
multiple puppet instances on the same device, even the same user, as
long as they inhabit different directories.

DEPENDENCIES
Requires git, tmux, rsync, and java (=17).

COMPATIBILITY
POSIX.1-2008 compatible, written entirely in portable shell script.
Should run on any remotely modern POSIX-compliant machine that is also
able to run tmux, java 17, and git.

Puppet is also explicitly designed for compatibility with
BusyBox 1.x.x and Alpine Linux 3.x.x.

Valid values for <option>:
  help: print this message and exit
  main: attaches to the main server (tmux attach-session)
  fallback: attaches to the fallback server (tmux attach-session)
  shutdown: shuts down the main server, without launching a fallback
  deploy: deploys from existing src and config, without updating
  deploy-all: updates source & config, deploys
  deploy-conf: updates configuration, use existing source and deploy
  deploy-src: updates source, use existing config and deploy
  setup: set up puppet in the current directory, if empty

-r: If <option> is one of deploy-all, deploy-conf, or deploy-src,
  deletes and re-clones the configuration and/or source repository.
  Otherwise does nothing. This is mainly useful if one of the git
  repository URLs defined in puppet.conf were updated."
    exit 0
fi

# Any other commands besides setup require $puppet_dir to exist first
[ -d "$puppet_dir" ] || die "must run setup first"

# Suppressed for the same reason as before. We're just loading config
# here.
# shellcheck disable=SC1090
. "$conf_file" || die "couldn't source $conf_file"

# At least we can error in the trivial case that the user didn't set
# the required config at all...
require_non_empty "$src_repo"
require_non_empty "$src_branch"
require_non_empty "$config_repo"
require_non_empty "$config_branch"

# Initialize both tmux servers appropriately, as we will likely need
# to be able to connect to them.
tmux_init "$socket_file_1"
tmux_init "$socket_file_2"

# Some commands are "exclusive" and shouldn't be run concurrently.
# Others aren't. Handle the commands that don't care about being run
# "simultaneously" first.
case "$1" in
    "main")
        tmux_attach "$main_socket_link"
        exit 0
    ;;

    "fallback")
        tmux_attach "$fallback_socket_link"
        exit 0
    ;;
esac

# The rest of the script should be "exclusive"; it should not be run
# concurrently in the same directory. Scripts in different
# directories may run concurrently.
mkdir -- "$lock_dir" ||
die "an instance of this script is already running"

# This is a false positive; the code can be run because it's in a
# trap.
# shellcheck disable=SC2317
exit_hook () {
    _old_exit_code="$?"
    rmdir -- "$lock_dir"
    return "$_old_exit_code"
}

trap 'trap - 0; exit_hook; exit' EXIT HUP INT QUIT ABRT TERM

case "$1" in
    "shutdown")
        bring_offline "$main_socket_link" "$main_log_pipe_link"
        exit 0
    ;;

    "deploy")
       # deploy requires existing code & config repositories, so make
       # sure those exist. Don't pull them.
       require_config
       require_code
    ;;

    "deploy-all")
        # Pull in the config and code repositories.
        update_config
        update_src
    ;;

    "deploy-conf")
        # Pull in just the config repository, and require the code
        # repository to exist already.
        require_code
        update_config
    ;;

    "deploy-code")
        # Pull in just the code repository, and require the config
        # repository to exist already.
        require_config
        update_src
    ;;

    *) die "unknown command $1" ;;
esac

# Note that -p here will resolve the symlink and test for the
# existence of the file pointed at by the link, rather than the link
# itself.
[ -p "$main_log_pipe_link" ]

# We are deliberately grabbing the result of the above condition, and
# storing it for later reference. This is maybe a bit odd, but it
# prevents us from needing to test multiple times.
# shellcheck disable=SC2319
_main_alive="$?"

[ -p "$fallback_log_pipe_link" ]

# Same rationale as above.
# shellcheck disable=SC2319
_fallback_alive="$?"

# 'dir_target' will already show an error message if it fails, so we
# don't need to do that here.
_main_dir=$( dir_target "$main_link" || exit 1; printf "." ) || die
_fallback_dir=$(
    dir_target "$fallback_link" || exit 1
    printf "."
) || die

_main_dir="${_main_dir%??}"
_fallback_dir="${_fallback_dir%??}"

# Neither server is alive. In this case, we just want to bring up the
# main server.
if [ "$_main_alive" -ne 0 ] && [ "$_fallback_alive" -ne 0 ]; then
    # This function will wait until the server comes online. If it
    # fails, it will call 'die' as appropriate, so we don't need to do
    # so here.
    bring_online "$_main_dir" \
    "$main_socket_link" \
    "$main_status_pipe_link"

    # There's nothing else to do, fallback isn't running. Exit.
    exit 0
fi

# Main is running; fallback isn't. We need to bring up fallback, and
# shut down main in an orderly fashion.
if [ "$_main_alive" -eq 0 ] && [ "$_fallback_alive" -ne 0 ]; then
    bring_online "$_fallback_dir" \
    "$fallback_socket_link" \
    "$fallback_status_pipe_link"

    bring_offline "$main_socket_link" "$main_log_pipe_link"

    # Everything went well; promote the fallback instance to the main
    # instance by swapping out the symlinks, then exit.
    promote_fallback "$_fallback_dir"
    exit 0
fi

# Other states such as fallback being alive while main isn't, or
# both being alive, are generally not permitted, and there's probably
# some sort of state corruption going on that we can't automatically
# fix.
die "invalid state"