#!/bin/bash

## Configuration

# Program name, can be changed in case of conflicts
pname="puppet"

# Install locations
bin_dir="/usr/local/bin"
data_dir="/usr/local/etc/$pname"
log_dir="/var/log/$pname"

# Directory where socket and PID files are stored
pid_dir="$data_dir/pid"

# Used to implement a simple folder-based mutex on this script
lock_folder="$data_dir/lock"

# 'main' and 'fallback' PID files
main_pid_file="$pid_dir/main.pid"
fallback_pid_file="$pid_dir/fallback.pid"

# Symlinks to the actual socket files
main_socket="$data_dir/main.sock"
fallback_socket="$data_dir/fallback.sock"

# Socket files
socket_1="$data_dir/socket_1.sock"
socket_2="$data_dir/socket_2.sock"

# Temporary log file, used to watch fallback server output
temp_log="$data_dir/log"

# Server directory
server_dir="$data_dir/servers"
server_1="$server_dir/server_1"
server_2="$server_dir/server_2"

config="$server_dir/config"
build="$server_dir/build"
src="$server_dir/src"
shared="$server_dir/shared"
blob="$server_dir/server.tar.gz"
persistent="$server_dir/persistent"

server_1_unique="$server_dir/unique_1"
server_2_unique="$server_dir/unique_2"

# Symlinks
main="$data_dir/main"
fallback="$data_dir/fallback"
logs="$persistent/logs"

# BEGIN USER CONFIG (should probably be changed by users before installing)
# Git repository branches
code_branch="dev"
config_branch="main"

# Repositories
config_repo="git@github.com-Configuration:PhantazmNetwork/Configuration.git"
code_repo="https://github.com/PhantazmNetwork/PhantazmServer"
# END USER CONFIG

check_dependency () {
  if ! which "$1" > /dev/null; then
    echo "Missing required program $1"
    false
  fi
}

require_root () {
  if [ "$user" != "root" ]; then
    echo "You must be root to run that command!" 1<&2
    exit 1
  fi
}

check_dependency tmux || exit 1
check_dependency git || exit 1
check_dependency rsync || exit 1
check_dependency tar || exit 1

user=$(whoami)

if [ "$1" == "install" ]; then
  require_root

  # Ensure that our current working directory exists
  cd "/" || exit

  script_file=$( readlink -f -- "$0" )

  if [ -f "$bin_dir/$pname" ]; then
    echo "$pname is already installed" 1<&2
    exit 1
  fi

  mkdir -p "$bin_dir"

  mkdir -p "$data_dir"
  mkdir -p "$log_dir"
  mkdir -p "$pid_dir"

  groupadd -f server_access

  # rwxrws--- perms on the data, log, and pid directory
  chmod 2770 "$data_dir"
  chmod 2770 "$log_dir"
  chmod 2770 "$pid_dir"

  # Ensure new files and directories are created with the correct permissions
  setfacl -d -m u::rwX,g::rwX,o::- "$data_dir"
  setfacl -d -m u::rwX,g::rwX,o::- "$log_dir"
  setfacl -d -m u::rwX,g::rwX,o::- "$pid_dir"

  chgrp server_access "$data_dir"
  chgrp server_access "$log_dir"
  chgrp server_access "$pid_dir"

  # Make all required files
  mkdir -p "$persistent"

  mkdir -p "$server_1"
  mkdir -p "$server_2"

  mkdir -p "$server_1_unique"
  mkdir -p "$server_2_unique"

  mkdir -p "$config"
  mkdir -p "$build"
  mkdir -p "$src"

  mkdir -p "$shared"
  mkdir -p "$persistent"

  ln -s "$log_dir" "$logs"

  # Create start script
  start_file="$persistent/start.sh"
  printf '#!/bin/bash\njava -Dfile.encoding=UTF-8 -jar server.jar' > "$start_file"
  chgrp server_access "$start_file"
  chmod 770 "$start_file"

  # Create the PID files
  touch "$main_pid_file"
  touch "$fallback_pid_file"

  # Create the tmux socket files
  tmux -S "$socket_1" new-session -d -n "server" -s "server" &> /dev/null
  tmux -S "$socket_2" new-session -d -n "server" -s "server" &> /dev/null

  # Set rw-rw---- perms on each socket
  chmod 660 "$socket_1"
  chmod 660 "$socket_2"

  # Create symlinks to the sockets, for switching the active server
  ln -s "$socket_1" "$main_socket"
  ln -s "$socket_2" "$fallback_socket"

  # Create symlinks to the server directories
  ln -s "$server_1" "$main"
  ln -s "$server_2" "$fallback"

  # Create the temporary log file
  touch "$temp_log"

  # Set up binary file, ensure it's owned by root
  cp "$script_file" "$bin_dir/$pname"
  chown root "$bin_dir/$pname"
  chgrp root "$bin_dir/$pname"
  chmod 755 "$bin_dir/$pname"

  echo "Installation complete. Some notes:"
  echo "* In order to allow users to use $pname commands, you must add them using $pname allow [user]."
  echo "* You will need to add worlds (or links to worlds) inside $persistent."
  echo "* Server files are located in $server_dir."
  echo "* Server logs are located in $log_dir."
  echo "* PID files are stored in $pid_dir."
  exit 0
fi

if [ ! -f "$bin_dir/$pname" ]; then
  echo "$pname has not been installed; do so by running '$pname install' with root permissions." 1<&2
  exit 1
fi

if [ "$1" == "uninstall" ]; then
  user=$(whoami)
  require_root

  rm -rf "$data_dir"
  rm -f "$bin_dir/$pname"
  rm -rf "$log_dir"

  rm -rf "$pid_dir"

  exit 0
fi

is_in_group () {
  groupname="$1"
  current_user="$(id -un)"
  user="${2:-$current_user}"

  for group in $(id -Gn "$user") ; do
    if [ "$group" = "$groupname" ]; then
      return 0
    fi
  done

  return 1
}

require_server_access () {
  if ! is_in_group server_access "$user"; then
    echo "'$user' is not part of the 'server_access' group!" 1<&2
    exit 1
  fi
}

require_blob () {
  if [ ! -f "$blob" ]; then
    echo "Missing required file '$blob'. Running '$pname deploy-src' should generate it, or else it can be brought in externally." 1<&2
    exit 1
  fi
}

update_config () {
  cd "$config" || exit 1

  if [ ! -d "$config/.git" ]; then
    rm -rf "$config"
    cd .. || exit 1
    git clone "$config_repo" "$config" || exit 1
    cd "$config" || exit 1
  fi

  git checkout "$config_branch" && git pull
}

if [ "$1" == "main" ]; then
  require_server_access
  tmux -S "$main_socket" attach-session
  exit "$?"
elif [ "$1" == "allow" ]; then
  require_root
  if [ -z "$2" ]; then
    echo "You must specify a user to allow!"
    exit 1
  fi

  usermod -aG server_access "$2" || exit 1
  tmux -S "$socket_1" server-access -a "$2"
  tmux -S "$socket_2" server-access -a "$2"
  exit 0
elif [ "$1" == "deny" ]; then
  require_root
  if [ -z "$2" ]; then
    echo "You must specify a user to deny!"
    exit 1
  fi

  usermod -rG server_access "$2" || exit 1
  tmux -S "$socket_1" server-access -d "$2"
  tmux -S "$socket_2" server-access -d "$2"
  exit 0
elif [ "$1" == "fallback" ]; then
  tmux -S "$fallback_socket" attach-session
  exit "$?"
elif [ "$1" == "shutdown" ]; then
  require_server_access
  tmux -S "$main_socket" send-keys -t "server" "orderly_shutdown" Enter
  exit "$?"
elif [ "$1" == "restart" ]; then
  require_server_access
  no_sync="true"
elif [ "$1" == "deploy-src" ]; then
  require_server_access
  rm -rf "$build" && mkdir "$build"

  update_config

  cd "$src" || exit 1
  if [ ! -d "$src/.git" ]; then
    rm -rf "$src"
    cd .. || exit 1
    git clone --recurse-submodules "$code_repo" "$src" || exit 1
    cd "$src" || exit 1
  fi

  git checkout "$code_branch" && git pull --recurse-submodules
  ./gradlew -PskipBuild=snbt-builder,dev-launcher,velocity phantazm-server:copyJar phantazm-server:copyLibs || exit 1

  cp -r "run/server-1/libs" "$build/" || exit 1
  cp "run/server-1/server.jar" "$build/" || exit 1

  tar -czf "$blob" -C "$server_dir" build || exit 1
elif [ "$1" == "deploy" ]; then
  require_server_access
  require_blob

  rm -rf "$build" && mkdir "$build"
  tar -xzf "$blob" -C "$server_dir" build || exit 1
elif [ "$1" == "deploy-conf" ]; then
  require_server_access
  require_blob

  update_config

  rm -rf "$build" && mkdir "$build"
  tar -xzf "$blob" -C "$server_dir" build || exit 1
elif [ "$1" == "help" ]; then
  printf "USAGE: %s OPTION\n\n" "$pname"
  printf "%s orchestrates Phantazm servers. It allows for safely re-launching with\n" "$pname"
  printf "updated configuration or code, without abruptly ending existing games.\n\n"
  printf "Valid values for OPTION:\n"
  printf "  help           Prints this help message and exits.\n"
  printf "  allow [user]   Allows a user to attach to or run servers. Requires root.\n"
  printf "  deny [user]    Denies a user to attach to or run servers. Requires root.\n"
  printf "  main           Attaches to the main server terminal.\n"
  printf "  fallback       Attaches to the fallback server terminal.\n"
  printf "  shutdown       Shuts down the main server.\n"
  printf "  restart        Restarts the main server, or starts it if it is not running.\n"
  printf "  deploy-src     Builds the server from source, synchronizes configuration,\n"
  printf "                 then launches (or restarts) it.\n"
  printf "  deploy-conf    Synchronizes configuration, then restarts the server. Requires\n"
  printf "                 the server.tar.gz file to exist.\n"
  printf "  deploy         Restarts the server. Requires the server.tar.gz file to exist.\n"
  printf "  install        Installs %s, if it is not already installed.\n" "$pname"
  printf "  uninstall      Uninstalls %s, if it is installed.\n" "$pname"
  exit 0
elif [ -n "$1" ]; then
  require_server_access
  echo "Unknown directive $1; try '$pname help' for more info" 1<&2
  exit 1
else
  require_server_access
  echo "Incorrect usage; try running '$pname help' for more info" 1<&2
  exit 1
fi

# Simple folder-based mutex
if ! mkdir "$lock_folder"; then
  echo "An instance of $pname is already running!" 1<&2
  echo "If this is an error, run 'rm -rf $lock_folder' and try launching $pname again." 1<&2
  exit 1
fi

exit_hook () {
  rm -rf "$lock_folder"
}

trap "exit_hook" EXIT

## Setup
tmux -S "$socket_1" new-session -d -n "server" -s "server" &> /dev/null
tmux -S "$socket_2" new-session -d -n "server" -s "server" &> /dev/null

## Function definitions

# Checks if a given process ID is empty or doesn't exist
check_status () {
  if [ -z "$1" ]; then
    echo "false"
  else
    if [ -z "$(ps -p "$1" -o args | grep -E "/usr/local/etc/$pname/(main|fallback)")" ]; then
      echo "false"
    else
      echo "true"
    fi
  fi
}

# Promotes the fallback server to the main server. Should be called if the fallback server is the only running server.
promote_fallback () {
  cat "$fallback_pid_file" > "$main_pid_file"
  echo "" > "$fallback_pid_file"

  new_active=$(readlink -f "$fallback_socket")
  new_server=$(readlink -f "$fallback")

  if [ "$new_active" == "$socket_1" ]; then
    old_active="$socket_2"
    old_server="$server_2"
  else
    old_active="$socket_1"
    old_server="$server_1"
  fi

  rm "$fallback_socket"
  rm "$main_socket"

  rm "$fallback"
  rm "$main"

  ln -s "$old_active" "$fallback_socket"
  ln -s "$new_active" "$main_socket"

  ln -s "$old_server" "$fallback"
  ln -s "$new_server" "$main"
}

synchronize_target () {
  if [ -z "$no_sync" ]; then
    target=$(readlink -f "$1")

    if [ "$target" == "$server_1" ]; then
      rsync -ac --delete "$server_1_unique/" "$persistent/" "$build/" "$config/" "$1" || exit 1
    elif [ "$target" == "$server_2" ]; then
      rsync -ac --delete "$server_2_unique/" "$persistent/" "$build/" "$config/" "$1" || exit 1
    else
      echo "Invalid synchronize symlink $1 -> $target; exiting (no server files have changed)" 1<&2
      exit 1
    fi
  fi
}

## Server startup

main_pid=$(cat "$main_pid_file")
fallback_pid=$(cat "$fallback_pid_file")

main_is_running=$(check_status "$main_pid")
fallback_is_running=$(check_status "$fallback_pid")

if [ "$main_is_running" == "false" ] && [ "$fallback_is_running" == "false" ]; then
  synchronize_target "$main"

  tmux -S "$main_socket" send-keys -t "server" "sh -c 'cd \"$main\"; echo \$\$ > \"$main_pid_file\"; exec ./start.sh'" Enter
  echo "" > "$fallback_pid_file"
elif [ "$main_is_running" == "true" ] && [ "$fallback_is_running" == "false" ]; then
  synchronize_target "$fallback"

  echo "" > "$temp_log"
  tmux -S "$fallback_socket" send-keys -t "server" "sh -c 'cd \"$fallback\"; echo \$\$ > \"$fallback_pid_file\"; exec ./start.sh | tee \"$temp_log\"'" Enter

  tail -f -q "$temp_log" | sed "/serverIP/ q"
  echo "" > "$temp_log"

  tmux -S "$main_socket" send-keys -t "server" "orderly_shutdown" Enter
  tail --pid="$main_pid" -f /dev/null

  promote_fallback
elif [ "$main_is_running" == "false" ] && [ "$fallback_is_running" == "true" ]; then
  echo "Warning: Invalid state detected, 'fallback' is alive but 'main' is not." 1<&2
  echo "$pname will attempt to promote the fallback instance to the main instance." 1<&2
  echo "If changes were deployed, they will not be visible in the new instance." 1<&2
  echo "You can try running $pname again to apply them." 1<&2
  promote_fallback
else
  echo "Both main and fallback are running! This is likely an error (did something break our mutex?), doing nothing." 1<&2
  exit 1
fi
