metadata.format.version = "1.1"

[versions]
caffeine = "3.0.6"

ethylene = "0.5.0"

jetbrains-annotations = "23.0.0"

junit-jupiter = "5.8.2"

minestom = "71b6e8df90"

miniMessage = "4.2.0-SNAPSHOT"

mockito = "4.3.1"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

ethylene-core = { module = "com.github.steanky:ethylene-core", version.ref = "ethylene" }
ethylene-toml = { module = "com.github.steanky:ethylene-toml", version.ref = "ethylene" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

minestom = { module = "com.github.Minestom:Minestom", version.ref = "minestom" }

miniMessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "miniMessage" }

mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
