metadata.format.version = "1.1"

[versions]
adventure = "4.10.1"

ethylene = "0.5.2"

junit-jupiter = "5.9.0-M1"


[libraries]
adventure-key = { module = "net.kyori:adventure-key", version.ref = "adventure" }

caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.0" }

ethylene-core = { module = "com.github.steanky:ethylene-core", version.ref = "ethylene" }
ethylene-toml = { module = "com.github.steanky:ethylene-toml", version.ref = "ethylene" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version = "0.53.0+1.18.2" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version = "0.14.6" }

fastutil = { module = "it.unimi.dsi:fastutil", version = "8.5.8" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

libgui = { module = "io.github.cottonmc:LibGui", version = "5.4.1+1.18.2" }

minecraft = { module = "com.mojang:minecraft", version = "1.18.2" }

minestom = { module = "com.github.PhantazmNetwork:Minestom", version = "486a27c506" }

miniMessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version = "4.5.1" }

renderer = { module = "com.github.Steanky:Renderer", version = "0923ca9be7" }

yarn-mappings = { module = "net.fabricmc:yarn", version = "1.18.2+build.3" }


[bundles]
fabric = ["fabric-api", "fabric-loader"]


[plugins]
fabric-loom = { id = "fabric-loom", version = "0.12-SNAPSHOT" }