instancesPath = ".\\lobbies"
kickMessage = "<red>Couldn't find where to send you!"
mainLobbyName = "main"

[lobbies.main]
lobbyPaths = [ "main" ]
maxPlayers = 10
maxLobbies = 10

[lobbies.main.instanceConfig.spawnPoint]
x = 0.0
y = 0.0
z = 0.0
yaw = 0.0
pitch = 0.0
