[serverInfo]
serverIP = "0.0.0.0"
port = 25567
optifineEnabled = true
authType = "BUNGEE"
proxySecret = "default"

[pingList]
description = "A Phantazm Server"

[pathfinder]
threads = 4
cacheSize = 2048
updateQueueCapacity = 1024
