[serverInfo]
    serverIP = "0.0.0.0"
    port = 25567
    optifineEnabled = true
    authType = "BUNGEE"
    velocitySecret = ""

[pingList]
    description = "A Minecraft Server"

[pathfinder]
    threads = 4
    cacheSize = 1024
